name: FFmpeg

on:
  workflow_dispatch:

jobs:
  ffmpeg_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ffmpeg
        uses: actions/checkout@v2
        with:
          repository: rdp/ffmpeg-windows-build-helpers
          path: ffmpeg
      
      - name: update packages
        run: | 
          sudo apt-get update && \
          sudo apt-get install subversion ragel curl texinfo g++ ed bison flex cvs yasm automake libtool autoconf gcc cmake git make pkg-config zlib1g-dev unzip pax nasm gperf autogen bzip2 autoconf-archive p7zip-full meson clang python3-distutils python-is-python3 -y
      
      - name: build ffmpeg
        run: |
          ffmpeg/cross_compile_ffmpeg.sh \
          --build-ffmpeg-static=y \
          --build-ffmpeg-shared=y \
          --build-intel-qsv=y  \
          --build-amd-amf=y \
          --disable-nonfree=n \
          --ffmpeg-git-checkout-version=n5.0 < 3

      - name: save build data
        uses: actions/upload-artifact@v2
        with:
          name: ffmpeg
          path: ffmpeg/

  